"""posts table

Revision ID: 1fe465d8244b
Revises: 
Create Date: 2025-05-25 10:17:35.008417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe465d8244b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(length=64), nullable=False),
    sa.Column('nome_empresa', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_nome_empresa'), ['nome_empresa'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_nome_usuario'), ['nome_usuario'], unique=True)

    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_configuracao', sa.String(length=200), nullable=False),
    sa.Column('valor_configuracao', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_user_id'))

    op.drop_table('configuracoes')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nome_usuario'))
        batch_op.drop_index(batch_op.f('ix_user_nome_empresa'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
