"""Add scraping tables

Revision ID: da99ad9d1672
Revises: 1fe465d8244b
Create Date: 2025-05-25 14:39:59.492490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da99ad9d1672'
down_revision = '1fe465d8244b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_marca', sa.String(length=45), nullable=False),
    sa.Column('nota_marca_avg', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('marcacol', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_marca')
    )
    op.create_table('origem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_site', sa.String(length=45), nullable=False),
    sa.Column('url_site', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(length=45), nullable=False),
    sa.Column('valor_produto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.Column('id_origem', sa.Integer(), nullable=False),
    sa.Column('nota_produto_avg', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('data_produto', sa.Date(), nullable=True),
    sa.Column('produtocol', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id_marca'], ['marca.id'], ),
    sa.ForeignKeyConstraint(['id_origem'], ['origem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(length=200), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('nota_avaliacao', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('data_avaliacao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacao')
    op.drop_table('produto')
    op.drop_table('origem')
    op.drop_table('marca')
    # ### end Alembic commands ###
